controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 1000  # Hz

    joint_states_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_effort_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_group_effort_controller:
  ros__parameters:
    use_sim_time: True
    joints:
        - FL_hip_controller
        - FL_thigh_controller
        - FL_calf_controller
        - FR_hip_controller
        - FR_thigh_controller
        - FR_calf_controller
        - RL_hip_controller
        - RL_thigh_controller
        - RL_calf_controller
        - RR_hip_controller
        - RR_thigh_controller  
        - RR_calf_controller  

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    
    gains:
      FL_hip_controller        : {p: 100.0, i: 0.0, d: 5.0, i_clamp: 2.5}
      FL_thigh_controller  : {p: 300.0, i: 0.0, d: 8.0, i_clamp: 2.5}
      FL_calf_controller  : {p: 300.0, i: 0.0, d: 8.0, i_clamp: 2.5}
      FR_hip_controller        : {p: 100.0, i: 0.0, d: 5.0, i_clamp: 2.5}
      FR_thigh_controller  : {p: 300.0, i: 0.0, d: 8.0, i_clamp: 2.5}
      FR_calf_controller  : {p: 300.0, i: 0.0, d: 8.0, i_clamp: 2.5}
      RL_hip_controller        : {p: 100.0, i: 0.0, d: 5.0, i_clamp: 2.5}
      RL_thigh_controller  : {p: 300.0, i: 0.0, d: 8.0, i_clamp: 2.5}
      RL_calf_controller  : {p: 300.0, i: 0.0, d: 8.0, i_clamp: 2.5}
      RR_hip_controller        : {p: 100.0, i: 0.0, d: 5.0, i_clamp: 2.5}
      RR_thigh_controller  : {p: 300.0, i: 0.0, d: 8.0, i_clamp: 2.5}
      RR_calf_controller  : {p: 300.0, i: 0.0, d: 8.0, i_clamp: 2.5}
